import React from "react";
import Head from "next/head";
import axiosClient from "../../libraries/axiosClient";
import numeral from "numeral";
import styles from "./products.module.css";
import { useRouter } from "next/router";

function ProductDetail(props) {
  const { product } = props;
  const router = useRouter();

  const onFinish = (values) => {
    console.log(values);

    // axios
    //   .post("/cart", values)
    //   .then((response) => {
    router.push("/cart");
    //     message.success("Thêm vào giỏ hàng thành công!", 1.5);
    //   })
    //   .catch((err) => {});
  };

  return (
    <>
      <Head>
        <title>Products</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {product ? (
        <div className={styles.product}>
          <img className={styles.product_images} alt="" src={product.img}></img>
          <div className={styles.product_details}>
            <h2 className={styles.h2}>{product.name}</h2>
            <h3 className={styles.h3}>
              Giá:{" "}
              <span style={{ color: "#ff3300", fontWeight: "bold" }}>
                {numeral(
                  product.price - (product.price * product.discount * 1) / 100
                ).format("0,0")}
                ₫
              </span>
              {product.discount > 0 && (
                <span
                  style={{
                    textDecoration: "line-through",
                    marginLeft: "8px",
                  }}
                >
                  {numeral(product.price).format("0,0")}₫
                </span>
              )}
            </h3>
            <h3 className={styles.h3}>
              Giảm giá: <span>{numeral(product.discount).format("0,0")}</span> %
            </h3>

            <div className={styles.about}>
              <p className={styles.p}>
                Tồn kho: <span>{product.stock}</span>
              </p>
              <p className={styles.p}>
                Mã sản phẩm: <span>{product._id}</span>
              </p>
            </div>

            <p className={styles.p}>{product.description}</p>
            <div className={styles.cta}>
              <div
                className={`${styles.btn} ${styles.btn_primary}`}
                onClick={onFinish}
              >
                add to cart
              </div>
              <div className={`${styles.btn} ${styles.btn_outline_secondary}`}>
                <span className={styles.material_symbols_outlined}>
                  add to wishlist
                </span>
              </div>
            </div>
          </div>
        </div>
      ) : (
        <span>Loading...</span>
      )}
    </>
  );
}

export default ProductDetail;

//SSG
export async function getStaticPaths() {
  return {
    paths: [],
    fallback: true,
  };
}

export async function getStaticProps(req) {
  try {
    const { params } = req;
    const response = await axiosClient.get(`/products/${params.id}`);

    return {
      props: {
        product: response.data.result,
      },
      revalidate: 10,
    };
  } catch (error) {
    console.log("err", error);
    return {
      notFound: true,
    };
  }
}
