GET http://localhost:9000/carts/6448c1cb1adbf9094a11ac53 HTTP/1.1
content-type: application/json

{ 
   "customerId": "642431ee35bf9d4ed2c41d34",
   "cartDetails": [
    {
        "productId": "643a3d4ac7561978bc899450",
        "quantity": 1
    }
   ]
}
