GET http://localhost:9000/carts/646baa5337ebafb3e60e689e HTTP/1.1
content-type: application/json

{
    "productId": "645147133a679930efa9cfe3",
    "quantity": 3,
    "customerId": "646baa5337ebafb3e60e689e"
}